INSERT INTO items (auction_id, seller_id, item_name, item_description, category, starting_price, final_price, item_status) VALUES
-- Ended Auctions (1–5), sold items
(1, 1, 'Handmade Clay Pot', 'A beautifully handcrafted clay pot.', 'Home Decor', 300.00, 450.00, 'sold'),
(1, 2, 'Organic Turmeric Powder', 'Pure, organic turmeric from farms.', 'Spices', 150.00, 180.00, 'sold'),
(2, 3, 'Traditional Saree', 'Elegant cotton saree with block prints.', 'Clothing', 1200.00, 1600.00, 'sold'),
(2, 4, 'Vintage Brass Lamp', 'Antique brass oil lamp.', 'Antiques', 800.00, 950.00, 'sold'),
(3, 5, 'Handwoven Basket', 'Eco-friendly basket made by artisans.', 'Crafts', 250.00, 300.00, 'sold'),
(3, 6, 'Organic Amla Juice', 'Boost immunity with 100% pure amla.', 'Health', 350.00, 375.00, 'sold'),
(4, 7, 'Ethnic Kurta Set', 'Designer kurta set with embroidery.', 'Clothing', 1400.00, 1700.00, 'sold'),
(5, 8, 'Wooden Photo Frame', 'Rustic frame carved by hand.', 'Home Decor', 500.00, 620.00, 'sold'),
(5, 9, 'Eco-Friendly Diya Set', 'Terracotta diya set for festivals.', 'Decor', 200.00, 250.00, 'sold'),
(5, 10, 'Spice Rack Combo', 'Set of traditional Indian spices.', 'Kitchen', 600.00, 750.00, 'sold'),
-- Auctions available items
(6, 1, 'Organic Honey', 'Raw honey collected from Himalayan bees.', 'Food', 400.00, NULL, 'available'),
(6, 2, 'Terracotta Vase', 'Elegant handcrafted vase.', 'Home Decor', 700.00, NULL, 'available'),
(7, 3, 'Bamboo Lamp', 'Sustainable and decorative lighting.', 'Lighting', 900.00, NULL, 'available'),
(7, 4, 'Khadi Shirt', 'Eco-conscious handwoven cotton shirt.', 'Clothing', 1100.00, NULL, 'available'),
(8, 5, 'Cane Tray', 'Rustic tray perfect for decor.', 'Crafts', 350.00, NULL, 'available'),
(8, 6, 'Copper Bottle', 'Ayurvedic benefits, leak-proof design.', 'Health', 800.00, NULL, 'available'),
(9, 7, 'Wool Shawl', 'Warm shawl woven in Himachal.', 'Clothing', 1500.00, NULL, 'available'),
(9, 8, 'Handmade Rug', 'Colorful dhurrie made from jute.', 'Home Decor', 2400.00, NULL, 'available'),
(10, 9, 'Ceramic Tea Set', '6-piece tea set with hand-painted design.', 'Kitchen', 1300.00, NULL, 'available'),
(10, 10, 'Natural Soap Bars', 'Assorted herbal soaps.', 'Beauty', 300.00, NULL, 'available'),
(11, 1, 'Recycled Paper Journal', 'Handcrafted journal made from recycled paper.', 'Stationery', 250.00, NULL, 'available'),
(11, 2, 'Jute Tote Bag', 'Stylish tote bag made from sustainable jute.', 'Fashion', 450.00, NULL, 'available'),
(12, 3, 'Ayurvedic Face Cream', 'Natural face cream with herbal ingredients.', 'Beauty', 650.00, NULL, 'available'),
(12, 4, 'Block Print Tablecloth', 'Cotton tablecloth with hand block prints.', 'Home Decor', 800.00, NULL, 'available'),
(13, 5, 'Glass Bead Necklace', 'Delicate necklace made of glass beads.', 'Jewelry', 500.00, NULL, 'available'),
(13, 6, 'Chili Powder Mix', 'Blend of organic chili powders from India.', 'Spices', 150.00, NULL, 'available'),
(14, 7, 'Silk Scarf', 'Luxurious handwoven silk scarf.', 'Fashion', 2000.00, NULL, 'available'),
(14, 8, 'Brass Candle Holder', 'Traditional brass candle holder with intricate designs.', 'Home Decor', 750.00, NULL, 'available'),
(15, 9, 'Herbal Tea Mix', 'A blend of organic herbs for calming tea.', 'Food', 350.00, NULL, 'available'),
(15, 10, 'Wooden Coasters Set', 'Set of 6 handcrafted wooden coasters.', 'Home Decor', 300.00, NULL, 'available'),
(16, 1, 'Cotton Beach Towel', 'Soft beach towel made of organic cotton.', 'Fashion', 400.00, NULL, 'available'),
(16, 2, 'Handmade Clay Bowl', 'A traditional clay bowl for cooking and serving.', 'Kitchen', 150.00, NULL, 'available'),
(17, 3, 'Herb Garden Kit', 'Complete kit to grow your own herbs at home.', 'Gardening', 550.00, NULL, 'available'),
(17, 4, 'Hemp Backpack', 'Sustainable backpack made from hemp.', 'Fashion', 900.00, NULL, 'available'),
(18, 5, 'Bamboo Toothbrush Set', 'Set of eco-friendly bamboo toothbrushes.', 'Health', 200.00, NULL, 'available'),
(18, 6, 'Woolen Mittens', 'Warm mittens woven in traditional style.', 'Fashion', 350.00, NULL, 'available'),
(19, 7, 'Handcrafted Wall Art', 'Wooden wall art with floral designs.', 'Home Decor', 600.00, NULL, 'available'),
(19, 8, 'Leather Wallet', 'Hand-stitched leather wallet with vintage finish.', 'Fashion', 1200.00, NULL, 'available'),
(20, 9, 'Crystal Chandelier', 'Elegant chandelier made of crystal beads.', 'Lighting', 3500.00, NULL, 'available'),
(20, 10, 'Scented Candles Set', 'Set of 3 hand-poured candles with natural scents.', 'Home Decor', 400.00, NULL, 'available'),
(21, 1, 'Wooden Jewellery Box', 'Handmade jewelry box with intricate carvings.', 'Jewelry', 550.00, NULL, 'available'),
(21, 2, 'Organic Herbal Shampoo', 'Shampoo made with all-natural ingredients.', 'Beauty', 350.00, NULL, 'available'),
(22, 3, 'Decorative Pillows', 'Handcrafted cotton pillows with colorful prints.', 'Home Decor', 800.00, NULL, 'available'),
(22, 4, 'Woolen Throw Blanket', 'Warm throw blanket made of 100% wool.', 'Home Decor', 1200.00, NULL, 'available'),
(23, 5, 'Cotton Beach Bag', 'Spacious beach bag made of soft cotton.', 'Fashion', 450.00, NULL, 'available'),
(23, 6, 'Herbal Foot Scrub', 'Organic foot scrub for smooth feet.', 'Beauty', 250.00, NULL, 'available'),
(24, 7, 'Jute Area Rug', 'Eco-friendly rug made from natural jute fibers.', 'Home Decor', 1500.00, NULL, 'available'),
(24, 8, 'Bamboo Cutlery Set', 'Sustainable cutlery set made from bamboo.', 'Kitchen', 400.00, NULL, 'available'),
(25, 9, 'Wooden Spice Rack', 'Rustic wooden spice rack with multiple compartments.', 'Kitchen', 900.00, NULL, 'available'),
(25, 10, 'Brass Wall Clock', 'Vintage-style wall clock made of brass.', 'Home Decor', 1800.00, NULL, 'available'),
(26, 1, 'Hand-painted Mug', 'Ceramic mug with traditional hand-painted designs.', 'Kitchen', 350.00, NULL, 'available'),
(26, 2, 'Cotton Beach Hat', 'Handwoven beach hat to protect from sun.', 'Fashion', 600.00, NULL, 'available'),
(27, 3, 'Saffron Powder', 'Organic saffron powder from Kashmir.', 'Spices', 700.00, NULL, 'available'),
(27, 4, 'Handmade Copper Mug', 'Traditional copper mug for drinking water.', 'Kitchen', 500.00, NULL, 'available'),
(28, 5, 'Decorative Wooden Bowl', 'Large wooden bowl for fruits and decor.', 'Home Decor', 1200.00, NULL, 'available'),
(28, 6, 'Herbal Facial Mask', 'Natural facial mask with Ayurvedic ingredients.', 'Beauty', 450.00, NULL, 'available'),
(29, 7, 'Leather Messenger Bag', 'Stylish leather bag for daily use.', 'Fashion', 2000.00, NULL, 'available'),
(29, 8, 'Hemp Journal', 'Eco-friendly journal made from hemp paper.', 'Stationery', 350.00, NULL, 'available'),
(30, 9, 'Jute Rug', 'Handwoven jute rug for rustic interiors.', 'Home Decor', 1000.00, NULL, 'available'),
(30, 10, 'Brass Wind Chime', 'Traditional brass wind chime with melodic sound.', 'Home Decor', 600.00, NULL, 'available');