INSERT INTO users (first_name, last_name, username, email, pass, address, account_balance, is_verified) VALUES
('Ananya', 'Gupta', 'ananya_gupta', 'ananya.gupta@gmail.com', 'password123', '123 Main Street, City, Uttar Pradesh, India', 5000.00, 1),
('Raj', 'Sharma', 'raj_sharma', 'raj.sharma@yahoo.com', 'p@ssw0rd!', '456 Elm Street, City, Maharashtra, India', 7000.00, 1),
('Rahul', 'Kumar', 'rahul.kumar', 'rahul.kumar@outlook.com', 'securepass', '789 Oak Street, City, West Bengal, India', 3000.00, 1),
('Sangeeta', 'Patel', 'sangeeta25', 'sangeeta25@gmail.com', 'myp@ssw0rd', '101 Maple Street, City, Tamil Nadu, India', 6000.00, 1),
('Vikram', 'Singh', 'vikram_singh', 'vikram.singh@yahoo.com', 'vikram123', '234 Pine Street, City, Karnataka, India', 4500.00, 1),
('Sonali', 'Joshi', 'sonali_89', 'sonali_89@outlook.com', '89$onali', '567 Cedar Street, City, Kerala, India', 5500.00, 1),
('Amit', 'Patil', 'amit_patil', 'amit.patil@gmail.com', 'p@t!l2023', '890 Birch Street, City, Punjab, India', 4800.00, 1),
('Shreya', 'Mishra', 'shreya.m', 'shreya.m@yahoo.com', 'shreya@12345', '1234 Willow Street, City, Uttar Pradesh, India', 6200.00, 1),
('Nikhil', 'Shah', 'nikhil_2000', 'nikhil_2000@outlook.com', 'nicenikhil', '5678 Cherry Street, City, Gujarat, India', 5100.00, 1),
('Priya', 'Verma', 'priya12', 'priya12@gmail.com', 'priyapassword', '9012 Walnut Street, City, Maharashtra, India', 5300.00, 1),
('Arnav', 'Kapoor', 'arnav.kapoor', 'arnav.kapoor@yahoo.com', 'arnav123!', '3456 Sycamore Street, City, Tamil Nadu, India', 6800.00, 1),
('Megha', 'Sen', 'megha.sen', 'megha.sen@outlook.com', 'sen_megha', '7890 Ash Street, City, Karnataka, India', 4200.00, 1),
('Vishal', 'Kumar', 'vishal32', 'vishal32@gmail.com', 'vishal#2024', '123 Oak Avenue, City, Kerala, India', 5700.00, 1),
('Anjali', 'Singh', 'anjali_11', 'anjali_11@yahoo.com', 'anjali@2023', '456 Elm Avenue, City, Punjab, India', 4900.00, 1),
('Ritika', 'Mishra', 'ritika.m', 'ritika.m@outlook.com', 'mritika!', '789 Cedar Avenue, City, West Bengal, India', 5500.00, 1),
('Harshit', 'Verma', 'harshit123', 'harshit123@gmail.com', 'harshit2023', '101 Maple Avenue, City, Tamil Nadu, India', 6200.00, 1),
('Sneha', 'Patel', 'sneha_04', 'sneha_04@yahoo.com', 'snehap@ssw0rd', '234 Pine Avenue, City, Karnataka, India', 4000.00, 1),
('Amar', 'Kumar', 'amar_kumar', 'amar_kumar@outlook.com', 'amar!kumar', '567 Cedar Avenue, City, Kerala, India', 4700.00, 1),
('Divya', 'Sharma', 'divya_09', 'divya_09@gmail.com', 'divya09@123', '890 Birch Avenue, City, Punjab, India', 5400.00, 1),
('Rohit', 'Bhatia', 'rohit.b', 'rohit.b@yahoo.com', 'rohitrohit', '1234 Willow Avenue, City, Uttar Pradesh, India', 5800.00, 1),
('Omar', 'Yasser', 'MARO_01', 'omaryasser05810@gmail.com', 'wordpass', 'Egypt', 999999.99, 1),
('Aditya', 'Kumar', 'aditya31', 'aditya31@gmail.com', 'aditya123!', '9012 Walnut Avenue, City, West Bengal, India', 6500.00, 1),
('Priyanka', 'Mehta', 'priyanka.m', 'priyanka.m@yahoo.com', 'priyankam@22', '3456 Sycamore Avenue, City, Tamil Nadu, India', 4700.00, 1),
('Rakesh', 'Singh', 'rakesh.singh', 'rakesh.singh@outlook.com', 'rakesh@12345', '7890 Ash Avenue, City, Karnataka, India', 5200.00, 1),
('Shivani', 'Gupta', 'shivani_g', 'shivani_g@gmail.com', 'shivani!23', '123 Oak Boulevard, City, Kerala, India', 4900.00, 1),
('Indian', 'Crafts', 'indian_crafts', 'indian_crafts@gmail.com', 'crafty@123!', '123 Main Street, City, Uttar Pradesh, India', 10000.00, 1),
('Organic', 'Farm', 'organic_farm', 'organic_farm@yahoo.com', 'organic4life!', '456 Elm Street, City, Maharashtra, India', 8500.00, 1),
('Fashion', 'Hub', 'fashion_hub', 'fashion_hub@outlook.com', 'fashionista2023', '789 Oak Street, City, West Bengal, India', 12000.00, 1),
('Spices', 'Galore', 'spices_galore', 'spices_galore@gmail.com', 'spiceitup!', '101 Maple Street, City, Tamil Nadu, India', 9500.00, 1),
('Tech', 'Store', 'tech_store', 'tech_store@yahoo.com', 'techgeek2023!', '234 Pine Street, City, Karnataka, India', 11000.00, 1),
('Aroma', 'World', 'aroma_world', 'aroma_world@outlook.com', 'aroma2023world', '567 Cedar Street, City, Kerala, India', 8000.00, 1),
('Greenery', 'Decor', 'greenery_decor', 'greenery_decor@gmail.com', 'greendecor21', '890 Birch Street, City, Punjab, India', 10500.00, 1),
('Desi', 'Dresses', 'desi_dresses', 'desi_dresses@yahoo.com', 'ethnicchic!', '1234 Willow Street, City, Uttar Pradesh, India', 9000.00, 1),
('Bookworm', 'Books', 'bookworm_books', 'bookworm_books@outlook.com', 'booklover23', '5678 Cherry Street, City, Gujarat, India', 11500.00, 1),
('Home', 'Appliances', 'home_appliances', 'home_appliances@gmail.com', 'homegadget123!', '9012 Walnut Street, City, Maharashtra, India', 9500.00, 1),
('Crafty', 'Creations', 'crafty_creations', 'crafty_creations@yahoo.com', 'createcraft2023', '3456 Sycamore Street, City, Tamil Nadu, India', 10200.00, 1),
('Wellness', 'Corner', 'wellness_corner', 'wellness_corner@outlook.com', 'wellnessliving!', '7890 Ash Street, City, Karnataka, India', 8800.00, 1),
('Organic', 'Beauty', 'organic_beauty', 'organic_beauty@gmail.com', 'naturalbeauty1', '123 Oak Avenue, City, Kerala, India', 10500.00, 1),
('Garden', 'Oasis', 'garden_oasis', 'garden_oasis@yahoo.com', 'greenoasis!', '456 Elm Avenue, City, Punjab, India', 9200.00, 0),
('Ethnic', 'Attire', 'ethnic_attire', 'ethnic_attire@outlook.com', 'ethnicfashion21', '789 Cedar Avenue, City, West Bengal, India', 10000.00, 0),
('Gadget', 'Galaxy', 'gadget_galaxy', 'gadget_galaxy@gmail.com', 'techwiz!2023', '101 Maple Avenue, City, Tamil Nadu, India', 11200.00, 0),
('Fitness', 'Freaks', 'fitness_freaks', 'fitness_freaks@yahoo.com', 'fitnessfan123!', '234 Pine Avenue, City, Karnataka, India', 9700.00, 0),
('Kitchen', 'King', 'kitchen_king', 'kitchen_king@outlook.com', 'kingofkitchen!', '567 Cedar Avenue, City, Kerala, India', 8800.00, 0),
('Home', 'Decor', 'home_decor', 'home_decor@gmail.com', 'decorstyle21!', '890 Birch Avenue, City, Punjab, India', 9900.00, 0),
('Beauty', 'Boutique', 'beauty_boutique', 'beauty_boutique@yahoo.com', 'beautyqueen2023', '1234 Willow Avenue, City, Uttar Pradesh, India', 10800.00, 0),
('Grocery', 'Galore', 'grocery_galore', 'grocery_galore@outlook.com', 'freshgroceries!', '5678 Cherry Avenue, City, Maharashtra, India', 9200.00, 0),
('Gadget', 'Hub', 'gadget_hub', 'gadget_hub@gmail.com', 'gadgetgenius21!', '9012 Walnut Avenue, City, West Bengal, India', 9800.00, 0),
('Fashion', 'Ista', 'fashionista', 'fashionista@yahoo.com', 'fashionforward!', '3456 Sycamore Avenue, City, Tamil Nadu, India', 10300.00, 0),
('Handmade', 'Hub', 'handmade_hub', 'handmade_hub@outlook.com', 'handmadeunique', '7890 Ash Avenue, City, Karnataka, India', 9300.00, 0),
('Pet', 'Paradise', 'pet_paradise', 'pet_paradise@gmail.com', 'petloverforever!', '123 Oak Boulevard, City, Kerala, India', 10600.00, 0);